### ISSUE TITLE
Channel selection via API

### ISSUE THREAD

**Issue by tischi** [fiji/TrackMate#100]
I am using this code to select the target channel:

`settings.detectorSettings.put(DetectorKeys.KEY_TARGET_CHANNEL, iChannel); 
`            

I realized that if iChannel is larger than the number of channels in the image it kind of "starts counting from the beginning".
For example, if there are the channels 0,1,2,3 and I select iChannel=5 it would take channel 1. 
I was just wondering if that is designed like this on purpose in order to prevent errors?

**Comment by tinevez** [comment]
No, I did not think of putting checks, and it defaulted on ImageJ behaviour.

**Comment by tischi** [comment]
Ok! Thanks for the info!
