### ISSUE TITLE
Sth about present trajectories 

### ISSUE THREAD

**Issue by jedyzdc** [fiji/TrackMate#102]
Dear Jean-Yves:
    Thank you for your amazing plugins! It is easy to use and give excellent and accurate result.
    Here is my question, and I hope you can give me a reply. The current trajectories mode shown on the images gives entire trajectories or local trajectories. However, I want the trajectories showing like this: when the particles start to move, the trajectories are plotted together with the particles. It is not 'show all entire trackers' mode, because this mode only gives all the trajectories at the very begining. And it is similar with 'local trackers, backwards' mode, but I need the previous trackers still  showing on the images.
    I don't know if it is possible to make it. And I think I will improve the results
Best
Dingcheng

**Comment by tinevez** [comment]
Hi @jedyzdc
You can do that by selecting `Plot local track backward`, but with unchecking the `limit frame depth` button.

![trackmate capture](https://cloud.githubusercontent.com/assets/3583203/26056163/65d377d6-3974-11e7-8918-959c511fd5ec.gif)

**Comment by jedyzdc** [comment]
Hi Jean-Yves:

   That is really cool! Thank you so much.

Best
Dingcheng



jedyzdc@gmail.com
 
From: Jean-Yves Tinevez
Date: 2017-05-15 19:43
To: fiji/TrackMate
CC: jedyzdc; Mention
Subject: Re: [fiji/TrackMate] Sth about present trajectories (#102)
Hi @jedyzdc
You can do that by selecting Plot local track backward, but with unchecking the limit frame depth button.
