### ISSUE TITLE
Capture overlay offset

### ISSUE THREAD

**Issue by rustyconc** [fiji/TrackMate#103]
Thanks for such a fantastic plugin. 

I know this wasn't a problem in an earlier version (unknown) that I tried.  However, now the capture overlay command captures the slice counter header of the image, and misses a bottom strip of image+overlay.  Looks like an offset is needed in the region to be captured?  

Thanks,
Russsell

Win10
Java 1.8.0_66
ImageJ 1.51n (FIJI)
TrackMate 3.5.1

**Comment by tinevez** [comment]
Hi @rustyconc 

I could not reproduce the bug, on the same platform. Do you have any specifics? Did you move the window during acquisition?

**Comment by rustyconc** [comment]
@tinevez Hmmm... attaching original image stack, trackmate xml file, and the capture export.  I have tried several times with different source images, and same result.  In all cases I simply executed the capture (mouse-click) and then did not touch the mouse again until completion.  Interestingly, where the image is on the screen (i.e. I moved the image before executing) seems to affect the amount of offset.  Enabling Windoze compatability setting "Disable display scaling on high DPI settings" had no effect.


[example.zip](https://github.com/fiji/TrackMate/files/1109708/example.zip)

**Comment by tinevez** [comment]
I am not sure you will like this, but I still cannot reproduce, despite trying on several computers.
Could it be something in the line of graphic display drivers the became awry? A Java version to update?

**Comment by rustyconc** [comment]
No other graphics issues on this machine, so could be quite the task to isolate here.  I have an easy workaround via TrackMate2MTrackJ and MTrackJ movie export, so probably not worth more of our time.  Thanks for the rapid responses!

**Comment by tinevez** [comment]
Well I will reopen this one if this ever happens to people...
