### ISSUE TITLE
Trackmate capture doing something real strange

### ISSUE THREAD

**Issue by l-jaye** [fiji/TrackMate#109]
Hello!

Great plugin, thank you!

I can't seem to export the overlays however.
This is what I am getting at the end of working thru the plugin:
![image](https://user-images.githubusercontent.com/32018129/31417327-b6a17800-adfc-11e7-9d82-7b593f327b49.png)

And this is what I get when I "Capture overlay" at the end of the plugin:

![image](https://user-images.githubusercontent.com/32018129/31417345-dace1fee-adfc-11e7-8c5e-5bb7a828b236.png)

It's real weird and different parts of my desktop pop into different frames of the exported image stack. I am not moving the original TIFF stack at while during processing, or capturing overlay.

Thanks for the help!

**Comment by tinevez** [comment]
Do you have multiple screens?

**Comment by l-jaye** [comment]
No, just on my laptop, but I am running Windows 10 on Mac via Bootcamp (it is my primary OS, iOS exists only for hardware drivers and I never boot into it). Perhaps this is messing with it?

I can try today on a true windows PC and get back to you :)

Thanks!

**Comment by tinevez** [comment]
Hi @l-jaye 
I actually _know_ about the big. It happened to me as well, _sometimes_. I was not able to diagnose it properly due to its stochastic appearance. 
Keep us posted nonetheless!

**Comment by l-jaye** [comment]
hello!

had no issues whatsoever on the true windows PC. So must be an issue with bootcamp drivers?

thanks!

**Comment by tinevez** [comment]
Nope. Happens on my mac too sometimes.

**Comment by tinevez** [comment]
You are not the only one btw: https://github.com/fiji/TrackMate/issues/103

**Comment by l-jaye** [comment]
Jean-Yves,

Can I contact you somehow about an un-related Trackmate question regarding
scripting?

Thanks!
-Julia

On Thu, Oct 12, 2017 at 3:55 AM, Jean-Yves Tinevez <notifications@github.com

**Comment by imagejan** [comment]
@l-jaye the best way is to ask on the [forum](http://forum.imagej.net/). This way, also others can benefit from the help when having similar problems.

**Comment by ajnarivera** [comment]
I'm having this exact same problem on Windows 10.  It happens every time I try to capture overlay.  Changing my display settings hasn't helped yet.  The left side is the results of tracking, the right side is the results of Capture Overlay
![capture](https://user-images.githubusercontent.com/34078672/33389015-6f2fb3fe-d4e6-11e7-81f2-853fdbc694be.GIF)

**Comment by nranthony** [comment]
Hi Jean-Yves, nice chatting with you at the Janelia conference.

Alas, I'm seeing the same issue with my capture:
![image](https://user-images.githubusercontent.com/16306836/37851553-babfddfc-2eb5-11e8-99bc-c2efcd77102e.png)
Please let me know what details you'd like from me to help you debug.
Thanks in advance for your time.
Neil

**Comment by nranthony** [comment]
I'm running windows 10.  I have two monitors; I tried disconecting one and restarting Fiji, but it's the same.  The steps I take are:
- open ome.tif in Fiji
- run trackmate
- swap z & t
- update the delta t from 1 frame to 66 ms and refresh trackmate
- run with pretty much default settings and create the overlay output

**Comment by nranthony** [comment]
Just to follow up.  I tried a different windows 10 PC, with a different GPU (Quadro vs GTX above) and it's the same.  There appears to be a strange offset that changes on the position of the window relative to each other.  See below for three captures overlaid and the offset within each.

![image](https://user-images.githubusercontent.com/16306836/38095456-85a64074-333e-11e8-98c6-407f4ce09133.png)

**Comment by tinevez** [comment]
Honestly I really do not know how to get this right. 
The class responsible for this is here:
https://github.com/fiji/TrackMate/blob/master/src/main/java/fiji/plugin/trackmate/action/CaptureOverlayAction.java

The class responsible for capturing the image is `java.awt.Robot`.
The bounds it captures are defined as follow:
``` java
final ImageWindow win = imp.getWindow();
win.toFront();
final Point loc = win.getLocation();
final ImageCanvas ic = win.getCanvas();
final Rectangle bounds = ic.getBounds();
loc.x += bounds.x;
loc.y += bounds.y;
final Rectangle r = new Rectangle( loc.x, loc.y, bounds.width, bounds.height );
```

And the capture is as simple as this:
``` java
final Image image = robot.createScreenCapture( r );
```

If anyone has an idea why __sometimes__ it fails, please come forward now.

**Comment by ctrueden** [comment]
@tinevez Not sure about the intermittent `java.awt.Robot` misbehavior. But this feature captures only the _inside_ of the image window, correct? If so, would it suffice to paint the canvas to a separate `BufferedImage` directly by calling `paint(Graphics)`? I whipped up an example to make sure it works: ctrueden/sandbox@fe1b2a090f83a21f40d5800899350ad64b1c7826. Might be issues with HDPI like Retina, but otherwise seems OK.

**Comment by tinevez** [comment]
@ctrueden 
Yup totally. The great Tobi also showed me that the proper way to export something was to have it paint on a different canvas. But I did not know how to do it for RGB capture. 
I will rewrite the exporter with your suggestion. Thank you so much!

**Comment by nranthony** [comment]
You guys are the greatest, and fast too!
Not that I understand the above exactly, but is it related to the strange 'zoom' option in Win10?

**Comment by tinevez** [comment]
Hi @nranthony, @ajnarivera, @l-jaye.
We hope we have a fix for the problem you describe. 
Could you please test the branch `fix-overlay-export` and tell me if now the capture works for you?

**Comment by nranthony** [comment]
Hi all,
It's fixed!  I cloned and built with Netbeans 8.2.  I changed the other trackmate jars (3.6 and 3.7) to jar.old and added the snapshot to that plugin folder and ran Fiji.  

Thanks for your time.  Excuse my pun, but I'll be pluging you plugin in the future with our core users.  It gives great results fast.  Wonderful stuff

Thanks
Neil

![image](https://user-images.githubusercontent.com/16306836/38211429-6d4d095c-3688-11e8-808e-5a0790431dcb.png)

**Comment by tinevez** [comment]
Awesome! Makes my day.
I am merging this and will release soon. 
Thank you for your feedback.

**Comment by ctrueden** [comment]
@l-jaye Two options:

1. Wait for @tinevez to upload a new TrackMate to the update site—then run _Help &#9654; Update..._ in Fiji to receive the update.

2. If you want the fix _now!_ :wink:, you can download the latest development snapshot from [here](http://maven.imagej.net/service/local/artifact/maven/redirect?r=snapshots&g=sc.fiji&a=TrackMate_&v=LATEST&e=jar), place it in your `Fiji.app/plugins`, and delete the old `Fiji.app/plugins/TrackMate-3.6.0.jar` (or whatever version you have there).

**Comment by l-jaye** [comment]
@ctrueden Thanks a ton!!!!!! I need some captures for a talk tomorrow, so perfect timing!!! Works great for me now :)
