### ISSUE TITLE
Non-homogenous subpixelic localization

### ISSUE THREAD

**Issue by MaximeMaW** [fiji/TrackMate#110]
Hi,

I have been recently analyzing fast single particle tracking data using TrackMate. To do so, I am computing the distribution of jump lengths (for which we have analytical derivations under free diffusion asumptions). The [Spot-On documentation](https://spoton.berkeley.edu/SPTGUI/docs/latest#the-problem) (among others) has an interactive plot about how the distribution is supposed to look like.

When doing that, I noticed that the plots have an extremly peculiar look, with wery sharp periodic peaks corresponding to the pixel size (160 nm in my case).

I am attaching below two examples, one with the detection made by DoG, the other using LoG. Both show the same trend. To me, it seems like the subpixelic localization fitting routine tends to "clip" the detections at one edge (or at the center I don't know) of the pixel, leading to the observed pattern.

This issue only happens with TrackMate, and I have processed the same file with MTT and get a smooth distribution as expected (see below). I have also tested 10+ files and get a similar result.

Would you have any idea how I could circumvent this issue? Right now this is rather blocking. I can provide a sample file if needed.

Thank you very much!

### LoG

![log_rtrban_fmmouna](https://user-images.githubusercontent.com/26774320/31472361-23c73450-aea3-11e7-8e7a-563197f933b6.png)

### DoG
![dog_9l7p9u_pmlv6nw](https://user-images.githubusercontent.com/26774320/31472369-310fbe66-aea3-11e7-9b1c-dfb4a3427dfb.png)

### MTT
![mtt_9xvros_pzd4wfa](https://user-images.githubusercontent.com/26774320/31472483-e5e877f6-aea3-11e7-89af-81c5f53e785f.png)

**Comment by tinevez** [comment]
This is probably a feature of the sub-pixel localisation technique we use, which is based on quadratic peak interpolation. 

This issue and the like generated previously much scrutiny and bug fixes. For instance:
 - https://github.com/fiji/TrackMate/issues/68
 - http://forum.imagej.net/t/trackmate-spot-detection-accuracy-question/4590
 - http://forum.imagej.net/t/accuracy-of-subpixel-localization-in-log-detector/181/16

We are now a bit more confident that the sub-pixel localisation is fixed. But coming back to your observations:

The quadratic fitting sub-pixel localisation we rely on is **not unbiased**. Even in the perfect situation, some sub-pixel shifts you see will be preferred over others. We picked this one because it was fast compared _e.g._ to gaussian fitting. 

To investigate and circumvent your problem I would take one of two paths:

 - Investigate the source of the spikes. How do they depend on the sigma parameter values in the LoG or DoG filters? Simulate images with blobs of the expected size and check what is the position TrackMate reports. It will depend on the choice of sigma in the LoG filter so you might have to look for an optimal one. The links cited above contain routines that might be useful for this test. 

 - Do not let TrackMate do sub-pixel localisation. Have the spot position detected with 1-pixel accuracy then performs your own sub-pixel localisation routine.

**Comment by MaximeMaW** [comment]
Hi,

Thank you very much for your quick response. I was not aware of the subpixelic localizer not being unbiased in noise-free conditions. I will come back to you with further tests, after playing with the sigma threshold.

On the other hand, it alternative fitting routines provide accurate subpixelic localization (at the expense of speed). Is there any plan to implement, for instance, gaussian fitting to trackMate? Alternatively, would a contribution in that direction be accepted?

Thank you very much!

**Comment by tinevez** [comment]
- At the current time no.
- Oh yes. So very much.
You can go two routes if you want to do that. 
- Either extend or copy the `LoGDetector` in another detector class and change the lines calling the sub-pixel localisation routine.  https://imagej.net/How_to_write_your_own_detection_algorithm_for_TrackMate
- Or create an `Action` that modify the spots location. https://imagej.net/How_to_write_custom_actions_for_TrackMate

**Comment by MaximeMaW** [comment]
Hi,

Thank you very much for the pointers. I will look into this and probably try to implement it as a detection algorithm rather than an action.

Meanwhile, I performed additional analysis, namely, I plotted the density of detections within a pixel for various detection algorithms:

![171023_pixel2d](https://user-images.githubusercontent.com/26774320/31924439-fa94f59e-b835-11e7-8091-bb9add830b91.png)

Each matrix represents an average camera pixel (160x160nm). I binned all the localization according to their position within the camera pixel (with 25x25 bins in that case). Axes are labelled as bins numbers and the binning represented here is 160/25 = ~6.4 nm/bin.

Although MTT (Sergé et al.) and thunderSTORM (Ovesny et al.) seem to be rather homogenous across a pixel, TrackMate is heavily skewed towards the pixel edges.

This is more visible when I compute the marginals along the x and y axis (normalized so that a value of 1 matches the expected value if detections are uniform in the pixel):

![171023_pixel1d](https://user-images.githubusercontent.com/26774320/31924464-36628dc0-b836-11e7-95e4-693e6c4013e6.png)

As I understand, the localization tends to "clip" the detection to the edge of a pixel, so that the detection occurs in the edge >500 times expected by chance (I obtained this number by binning a pixel into a 100x100 submatrix). Also, this behavious seems to occur only in one dimension.

Is that the bias you mentioned in your previous post? Or is that a bug (to me, the fact that it only occurs in one dimension suggest that there is an issue with the routine).

I am currently running the localization with various "blob sizes" and will report about that later this week.

Thanks a lot,

**Comment by tinevez** [comment]
Humm now I am full of doubts. This is something worth investigating.

**Comment by MaximeMaW** [comment]
Hi,

I was able to understand where the issue comes from. The "clipping" occurs when a particle is detected at the edge of the image:

- Since my image had a weird aspect ratio, clipping happened more often across the y axis than the x axis
- I guess this effect becomes visible when there are a lot of particles (in my case, >0.5 million detections)
- I tested the role of the blob size, and for my image, either the default (0.48 µm, ie 3px) or 0.68 µm yield the same effect.

The good news is that if I filter the detections according to x and y position (x>1/2px and x<x_max-1/2px, same in the y dimension), the bias becomes much more reasonable (and totally acceptable in my view), see the images below:

![171023_pixel2d_filtered](https://user-images.githubusercontent.com/26774320/31962750-480eebc2-b8b3-11e7-9cce-8a74cee345fc.png)

![171023_pixel1d_filtered](https://user-images.githubusercontent.com/26774320/31962671-09dd2634-b8b3-11e7-8324-7752838f6fe8.png)

Thus, it seems that the issue does not directly lies in the subpixelic localization routine, but rather in TrackMate not filtering out these detections. In my view, when the subpixelic localization is activated, it would make sense to filter out these detections that occur at the edge of the image because they only contribute to coruption and artifacts in the tracking.

Do you have any thoughts about that?

**Comment by MaximeMaW** [comment]
@tinevez, would you have any thought about my previous message? Thanks!

**Comment by MaximeMaW** [comment]
Hi @tinevez,

So I made a first attempt to write an action that filters those detections, as you initially suggested ([GitLab link](https://gitlab.com/padouppadoup/Trackmate-filter-exportXML)). The plugin works, but as you might guess, this is not a satisfactory workaround, because it adds gaps to a track, potentially breaking downstream analyses, or event generating empty tracks.

I was wondering what would your opinion be about integrating the filtering at the detection step, and not as an action. Thanks!
