### ISSUE TITLE
TrackMate does not warn the user before overwriting files

### ISSUE THREAD

**Issue by MaximeMaW** [fiji/TrackMate#111]
Hi, I noticed that when I click the "Save" button at the bottom left corner of the interface, or the "Export tracks to XML file" button in the action panel, TrackMate does not warn the user if it is about to overwrite an existing file.

This is an unconventional behaviour compared to the softwares I am used to. Is that intentional?

Thank you very much

**Comment by tinevez** [comment]
Mouhahahahahahaha :trollface: 😈

**Comment by tinevez** [comment]
More seriously I will fix this in the next release.

**Comment by tinevez** [comment]
I did not :(
