### ISSUE TITLE
TrackOverlay disappears from PNG, and neither show up in imp.getOverlay()

### ISSUE THREAD

**Issue by l-jaye** [fiji/TrackMate#112]
Hi @tinevez !

Fantastic plugin!

We are running it via Jython script to automate processing of multiple images, and at this point, the last remaining problem is trying to save the hyperstack view of the first 20% of slices, at the end of each trackmate cycle.

However, when I flatten a slice, it only shows the spots overlay (and I believe all of them the same from the first slice, not from the current slice). The tracks are missing for me.

Furthermore, before flattening, when I run imp.getOverlay().size(), it returns 2. I assume one is for spotOverlay, the other is the trackOverlay. However, when I run imp.getOverlay().toArray(), it seems the ROIs are empty:

`array(ij.gui.Roi, [Roi[Rectangle, x=0, y=0, width=0, height=0], Roi[Rectangle, x=0, y=0, width=0, height=0]])`

imp is returned as not a hyperstack, not displayed as a hyperstack, nor a composite. 

I noticed that the CaptureOverlayAction code uses a screen grabber, which I am having issues with, so I would prefer to just flatten the overlay and save the stack like that, but it's not including the TrackOverlay, and doesn't return any ROIs. Just wondering if you could help?

Thank you!

**Comment by tinevez** [comment]
Hi @l-jaye 

I am afraid the `flatten` command won't be working. We have used an ImageJ1 `Overlay` and `Roi` as base classes and interfaces, but that was just to be able to plug into an `ImagePlus`. So it is 'normal' that you find the Roi to be empty. 

For TrackMate the only thing I could come up to capture the overlay was to use the `ScreenGrabber` trick you found in the `CaptureOverlayAction`. Indeed it has issues, see for instance  #109. But this is all I have for TrackMate.
