### ISSUE TITLE
Spots from Frame 2 all discarded when tracked with linear motion tracker

### ISSUE THREAD

**Issue by hadim** [fiji/TrackMate#113]
@tinevez 

I think I found a bug in the linear motion tracker. When used, all the detected spots on **Frame 2** are discarded. It does not happen with the other trackers.

You can reproduce this with the Trackmate sample without configuring anything just clicking next on the GUI.

**Comment by seamusholden** [comment]
Can confirm this bug.
It is also specific to the linear motion tracker. Eg, spots from Frame 2 are retained in the simple LAP tracker.

**Comment by tinevez** [comment]
I have a crazy request: Could you send me a short TrackMate file that demonstrate the problem and that I could use to solve it?

**Comment by seamusholden** [comment]
Absolutely. Thanks for following this up! Hopefully this should work. Included the movie as well. Dataset is tracked with the LinearLAP tracker and as you can see all the tracks are missing frame 2.

[testKalmanTracker.zip](https://github.com/fiji/TrackMate/files/1818887/testKalmanTracker.zip)

**Comment by bernhardw13** [comment]
Is there any news on this issue?

I ran into the same problem. When I use the linear motion LAP tracker and export tracks to XML file frame 2 is missing in the tracks in the XML file. Frames 0, 1 and >2 are there.

**Comment by tinevez** [comment]
_Investigate_

**Comment by ctrueden** [comment]
> Investigate

@tinevez I suggest using one of GitHub's tools for flagging it, so you remember. You could assign yourself, and/or create an `investigate` or `to do` label and add that.

**Comment by tinevez** [comment]
Bug confirmed.
