### ISSUE TITLE
Capture Overlay in TrackMate is offset

### ISSUE THREAD

**Issue by etarena** [fiji/TrackMate#114]
This issue was originally posted by @ajnarivera on the [imagej/imagej repository](https://github.com/imagej/imagej/issues) here: [#181](https://github.com/imagej/imagej/issues/181).

I've tried Capture Overlay several times, including after restarting my computer.  Each time it produces an offset clip:
![capture](https://user-images.githubusercontent.com/34078672/33350366-379d2e00-d453-11e7-8c4b-22720e0176a4.GIF)

**Comment by tinevez** [comment]
Yep. And I do not know how to fix it yet.

**Comment by tinevez** [comment]
Duplicate of #109
