### ISSUE TITLE
Add a detector to Trackmate that runs two detections with two different diameters

### ISSUE THREAD

**Issue by etadobson** [fiji/TrackMate#115]
As suggested by @hadim on the ImageJ Forum on a [post](http://forum.imagej.net/t/particle-tracking-in-video-s/9258) by a user wishing to track differently-sized objects in the same field-of-view.  

As he said, it "would be nice to add a detector to Trackmate that run two detections with two different diameters. It should not be that hard since it would basically be a wrapper over the already existing detectors."

**Comment by tinevez** [comment]
_Do when I am commissioned to._

**Comment by tinevez** [comment]
Solved with TrackMate v7, released today.
