### ISSUE TITLE
Spot interpolation leads to NullPointerException spam

### ISSUE THREAD

**Issue by alexdukhno** [fiji/TrackMate#119]
Hello

I've noticed a peculiar behavior with Trackmate: when I treat the image stacks, everything goes perfectly fine until the very last window, where one can choose operations like exporting to XML. After that, if I choose the option of interpolating missing points, the plugin works fine, deactivates the execute button, but then starts spitting out copious amounts of "Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException" in console. Frustratingly, it doesn't give back a stack trace to diagnose the error.
What's curious is if you let it sit around and work for a bit, ignoring the errors, it eventually finishes the job and activates back the execute button. However, it works extremely slowly (probably due to constant callbacks to output the same exception to Fiji console). Outputting to XML after this also works okay and gives a proper file with proper interpolation. 
Stack is 1500 frame 512x512x16 bit greyscale, with ~600 tracks found by Simple LoG algorithm. Most of the found tracks are about 100 frames long. Trackmate and Fiji version are recent as of this date. ImageJ is given 6 GB memory, albeit Windows task manager shows it using only 3.3 GB.
Any advice concerning this issue would be appreciated, as it is currently the bottleneck in the treatment of our results. :no_mouth:

Thanks and best regards
Alex

**Comment by tinevez** [comment]
@haesleinhuepf could you check this?

**Comment by tinevez** [comment]
No news.
