### ISSUE TITLE
[enhancement] blob tracking for cell centroid tracking as well as shape descriptor tracking

### ISSUE THREAD

**Issue by hftsai** [fiji/TrackMate#121]
Dr. Tinevez,
Trackmate has been great. I read about this issue on the FAQ. i just want to possible ask again for your thoughts about what kind of approach is possible to enable trackmate to track irregular rois?
Since this approach will be greatly helpful for cell migration analysis.
I think right now segmentation can be done else where for better results to generate binary masks. But tracking multiple objects with shape descriptors are really challenging and i haven't find a good approach for this.

is it possible to hardness the wand tool?
or maybe just linking the rois in each frame that can be generated after "particle analysis" ?

Thank you

**Comment by tinevez** [comment]
I think this is something the great @stelfrich started doing. Stephan, care to comment?

**Comment by stelfrich** [comment]
> I think this is something the great @stelfrich started doing.

Thanks for the 💐!

> Stephan, care to comment?

Indeed, I have worked on that quite some time ago and have a running version somewhere. I will not have time to dig into it this week but I might find some time next week. Just to get my priorities straight: @hftsai, do you require information from the original image from which the binary mask was created (e.g. intensities)?

**Comment by hftsai** [comment]
Hi Stelfrich ,
Thank you so much.
What i have imagined is to obtain a linked rois to allow me to track centroid as well as all other shape descriptors (fit ellipse, circularity etc)
Do you think it's something doable?

Thank you so much

**Comment by stelfrich** [comment]
> Do you think it's something doable?

I have links to `Roi`s in the implementation s.t. it should be possible to extract the quantities you have mentioned. I will look into making my implementation more generic to operate on binary images (which should avoid some of the `Overlay` discussions from #17) next week.
