### ISSUE TITLE
Tracking blinking spots

### ISSUE THREAD

**Issue by ririya** [fiji/TrackMate#125]
Hi everyone,

I’m using the LAP tracker and I noticed that Trackmate fails to connect segments if no connection is found between adjacent frames.

For example, if a particle is blinking on and off and it’s only detected on the even frames but missed on the odd frames, no track is generated, even if the distance between detections is within the gap closing threshold.

Is there any way to overcome this problem?

Here is a sample dataset. I created some fake tracks to illustrate the problem. Spots are moving with velocity (5,5) between frames. Lower spot blinks on and off and I cannot generate a track for it.

https://www.dropbox.com/sh/4fktxs6tuk6nc5a/AABZLrOSSN6FjXZLSIpDCMdga?dl=0

**Comment by ctrueden** [comment]
Maybe you could downsample/bin the data over time, to eliminate the blinking effect?

**Comment by ririya** [comment]
On my dataset the blinking is random, i believe downsampling will accentuate the problem. I am thinking of increasing the framerate, but I wanted to know if there is a software solution for this...

**Comment by imagejan** [comment]
Please note that this issue was first raised [in this topic](http://forum.imagej.net/t/imagej-tracking-blinking-spots-problem/10604?u=imagejan) on the ImageJ forum.

@ririya please always link when cross-posting, so that others can follow the discussion.

**Comment by ctrueden** [comment]
> On my dataset the blinking is random, i believe downsampling will accentuate the problem.

Maybe a rolling max projection window then, to eliminate gaps for the purposes of segmentation and linking?

**Comment by ririya** [comment]
@ctrueden I think any pre-processing to the images will create artifacts that are undesirable to me. I need a very robust detection of spots, with a very good resolution between two close spots. 

Filling gaps will also be hard because there are a lot of spots. Finding the right direction for filling the spots is almost the same as performing tracking. Moreover, sometimes the spot goes missing for several consecutive frames...

I think your ideas are good but they would need a faster frame rate

**Comment by tinevez** [comment]
I will look into this issue starting next week, as I am currently away from the lab. 
Can I get the parameters to reproduce the problem?

**Comment by tinevez** [comment]
Argh you are perfectly correct. To solve your issue we have to develop a new, specialized tracker.

**Comment by tinevez** [comment]
What about writing a tracker specific for blinking particles? Bonneaud et al. published one in 2008 but there are no implementation available today.

**Comment by impact27** [comment]
I had the same problem and the easy fix was to duplicate all the frames. This adds all single particles to a track, which can then be liked. Of course it is not ideal as I have to post-process the results, and the videos are twice as large as they should be.
Would it be possible to add an option so that every particle that are not in a track be added to a track with a single frame? So that when the algorithm links the tracks together, they are considered?

**Comment by impact27** [comment]
If all the spots are added to the graph, would ConnectivityInspector count single spots as length 1 tracks?

**Comment by tinevez** [comment]
Argh no.
We specifically impose segments to have at least one **link**. So we need at least 2 spots. If we change this we might break TrackMate elsewhere, in particular loading and saving.
I strongly encourage you to fix this issue *by implementing a specific tracker that can harness this*, not hanging the core of TrackMate.

**Comment by tinevez** [comment]
Yes that would be the difference to implement. The LAP tracker in its 2nd step only considers linking between track _segments_ and segments are at least 2 spots long.
The change you propose would be to make a new tracker that allows for incorporating free spots to segments in this 2nd step.
