### ISSUE TITLE
Video Downscaling

### ISSUE THREAD

**Issue by chillywings** [fiji/TrackMate#128]
Hi,

Hopefully this is an easy answer. It's come to my attention that the tracks that TrackMate outputs are scaled down relative to the original video. Eg, for a video with a resolution of 1376x1104, the highest x,y values are 364 and 292, respectively. There are definitely objects/tracks beyond that in the video, so I interpret this as a downscaling of the video by 3.78x. Is there a reason this is happening or something I can do to prevent it? 

Thanks,
Marcus

**Comment by tinevez** [comment]
This depends on the pixel size. 
If your pixel size is whatever fraction of 1, your coordinates will be different from the pixel position. Come and discuss this on the forum.image.sc
