### ISSUE TITLE
Spots in track statistics for Splitting Events

### ISSUE THREAD

**Issue by jeffreyeyeung** [fiji/TrackMate#133]
Hi @tinevez,

Apologies if this has a simple solution but when a track has a splitting event, exporting spot statistics seems to ignore it, showing statistics for only one spot even after the split event. 

Is there a way to get statistics on all spots even after the splitting event? Thanks for any help.

**Comment by tinevez** [comment]
Hello @jeffreyeyeung 

This does not sound right at all.
Can you give me a way to reproduce the issue?

**Comment by tinevez** [comment]
Hello @jeffreyeyeung 
Any news?

**Comment by jeffreyEdgarYeung** [comment]
Apologies for the late response. It turned out to be a case of malformed input. After re-running track mate, I was able to finds statistics for both tracks.

**Comment by tinevez** [comment]
Ok! Thank you for this update.
Closing the issue.
