### ISSUE TITLE
Inputting hand-generated XML with detected spots for interfacing with TrackMate's linking algorithms

### ISSUE THREAD

**Issue by cynashirazinejad** [fiji/TrackMate#135]
Hi!

I have generated an XML file in a format resembling one generated by the TrackMate GUI with my own detection/filtering scripts that creates instances of spots throughout the frames of my movie. I was hoping to link this directly into TrackMate with a Python script. This would be analogous to loading an XML file into the GUI as an intermediate between filtering>detection and tracking. Is this possible and are the codes that exist to already achieve this? Thank you for looking at my question--I am excited to get this working!

Cheers,
Cyna

**Comment by tinevez** [comment]
Hello Cyna.
I saw you asked this question on the forum. I am therefore closing this issue.
