### ISSUE TITLE
Features request: jump to next frame after adding a track

### ISSUE THREAD

**Issue by SarenT** [fiji/TrackMate#139]
Some colleagues of mine prefer the more inferior tool (manual tracking) due to the simplicity of manual tracking. Advantage there is that once user starts clicking to add spots, video jumps automatically to the next frame. User interaction is minimized by 1 click per spot instead of clicking + scrolling. This seems to be a small difference but manual tracking is exhaustive and any ease of use is welcomed. I may look into this myself if I find the time. It doesn't seem to be difficult problem to solve. The switch "L" for automatic linking may be coupled in this case to move to next frame.

**Comment by tinevez** [comment]
Hi @SarenT 
This is a good idea, but I am frowning about it for now. 
With the auto-link mode (`L`) when we create a spot it is immediately linked to the one previously selected.
I feel like if we move immediately and automatically to the next frame after that, we loose the possibility to check that the new spot and link are consistent.
What I do in practice is using the keyboard 'G' key to move in time and 'A' to add a spot. It is less automatic but by not much.

**Comment by SarenT** [comment]
Hi @tinevez,
I agree that this may confuse users. But optionally, another mode with another key can be implemented. When both auto-link and auto-move-next are activated, then it moves to next frame after adding a spot. Otherwise, it doesn't. Users can still scroll or follow TrackScheme on another window for checks.
G and A are still two clicks. If each track consists of >100 of points with multiple tracks, this has a great impact on user experience. Again, I will try to implement this anyhow, once I will get the chance.
