### ISSUE TITLE
Bug in "Capture Overlay"

### ISSUE THREAD

**Issue by MaximeMaW** [fiji/TrackMate#140]
Hello!
I have the feeling that when running the "export overlay" option, the first frame of the movie is not included.

**Steps to reproduce**:
- Track a movie (I tried with a 3D movie, but I don't think that it matters)
- Capture overlay on frame 1 (*from:* 1 *to:* 1)
- Look at the resulting image: it is frame 2, and not frame 1.

I haven't found a simple way to circumvent this. Would you have any advice? Many thanks!

**Comment by tinevez** [comment]
Hello @MaximeMaW 
You are perfectly right!
The capture starts at the 2nd frame. The last frame is added a second time at the end of the capture.
I guess I mixes things up with 0-based vs IJ 1-based indexing.
Thanks!

**Comment by MaximeMaW** [comment]
Awesome, many thanks, that was such a quick fix!!!
