### ISSUE TITLE
Nearest Neighbor(NN) search returns different result per each trial

### ISSUE THREAD

**Issue by SosUts** [fiji/TrackMate#148]
Hi, I'm using TrackMate for single molecule analysis.  
I noticed that NN search produce different spot linking results(e.g. number of tracks) even though the parameters are exactly the same.  
Number of spots are always the same.  
Why does this happen?  
Is pseudo random numbers used in NN?  

I'm not a native English speaker, I'm sorry for my poor English...
**What I want to say**
Spot detection(number of spots1) -> NN(tracking result1) -> reboot TrackMate ->
Spot detection(number of spots2) -> NN(tracking result2)
number of spots1 == number of spots2
result1 != result2

**Comment by tinevez** [comment]
Yep.
See our discussion here: 
https://forum.image.sc/t/nearest-neighbor-nn-linking-in-trackmate-returns-different-result-per-each-trial/33696/3
