### ISSUE TITLE
TrackMate uses SciJava priorities in an inversed way

### ISSUE THREAD

**Issue by imagejan** [fiji/TrackMate#150]
TrackMate implements its own way of handling SciJava priorities.

While this is documented in the [wiki tutorial for developers](https://imagej.net/How_to_write_your_own_spot_feature_analyzer_algorithm_for_TrackMate#Using_SciJava_priority_to_determine_order_of_execution), it is not obvious from looking at the [example code](https://github.com/fiji/TrackMate-examples/blob/bf184b74569231551c8c5055b5ce31f140341699/src/main/java/plugin/trackmate/examples/spotanalyzer/RelativeIntensitySpotAnalyzerFactory.java#L26), and can create headaches for developers familiar with SciJava but not TrackMate.

The code in question is in two places in this repository:

https://github.com/fiji/TrackMate/blob/be62ab107ba5e5b6d6cfa0acc344e31da8da829f/src/main/java/fiji/plugin/trackmate/providers/AbstractProvider.java#L43-L49

https://github.com/fiji/TrackMate/blob/be62ab107ba5e5b6d6cfa0acc344e31da8da829f/src/main/java/fiji/plugin/trackmate/providers/ViewProvider.java#L80-L87

In `scijava-common`, priorities compare as implemented [here](https://github.com/scijava/scijava-common/blob/560ad964a7a1e859edd4dbe4fc48d7d9e09523f2/src/main/java/org/scijava/Priority.java#L89-L115):

```java
		// NB: We invert the ordering here, so that large values come first,
		// rather than the typical natural ordering of smaller values first.
		return priority1 > priority2 ? -1 : 1;
```

---

For the sake of future consistency, we should consider changing the priority handling and use SciJava's `Priority.compare()` everywhere.

Of course, this might break the order of executions of third-party plugins, but we could probably cope with this in reality by setting the priority of the built-in modules to `Priority.LOW` or some such.

**Comment by tinevez** [comment]
True.
I was young at the time.

**Comment by ctrueden** [comment]
You shouldn't have to sort at all, because all those `PluginService` methods for retrieving plugins should already return results ordered by priority.

**Comment by tinevez** [comment]
This branch is going to be deleted so we should fix this issue again in another branch maybe.

**Comment by ctrueden** [comment]
@tinevez I filed #154 with this patch over the latest master. I hope that's what you meant.
