### ISSUE TITLE
Measuring intensities before and after the tracking event

### ISSUE THREAD

**Issue by SimonaKavaliauskiene** [fiji/TrackMate#157]
I would like to use TrackMate to measure whether binding of the protein (the tracking events I am measuring) affects the signal in another channel (reporter protein). To do so, I need to have the baseline (signal intensity during 3-5 frames before and after detection happened; in the same area as the start and the end of the event) for the channels. I am considering trying to add this functionality, but since I am just a beginner in programming, this might take a while :) anyone, willing to do it faster?

**Comment by tinevez** [comment]
Hello @SimonaKavaliauskiene. I am closing this issue for now, as there is no follow up that I know of.
