### ISSUE TITLE
Problem_Track Analysis Extension and TrackMate v6.0.0

### ISSUE THREAD

**Issue by BesseLaetitia** [fiji/TrackMate#159]
Hello,
Following the update of Fiji, we noticed a problem by using the version TrackMate v6.0.0 associated with the extension Track Analysis downloaded from https://imagej.net/TrackMate.html#Extensions. For this extension, we downloaded the .jar files.
In fact, we got an error (see red lines below) and we obtained a table Tracks statistics with columns filled with "None" values.
Do you know how to correct this ?

For the moment, we use an old version of Trackmate (v3.4.2, from a version of Fiji download on internet without update) associated with the extension Track analysis and it's working. 

Thank you in advance for your help.

Laetitia Besse (light microscopy MIC@Orsay Institut Curie).

![TrackMate Error](https://user-images.githubusercontent.com/70573939/91849588-963dcb80-ec5c-11ea-88bd-256905603e04.png)
![Tracks statistics error](https://user-images.githubusercontent.com/70573939/91849593-96d66200-ec5c-11ea-8421-aded8b868c0d.png)

**Comment by Raghavendrapara** [comment]
trackValueFeatures Map seems like un initialised. trackID key's corresponding Value is giving a Null Pointer Exception.

Seems some new code calls the FeatureModel class without calling appropriate method for intialising the Map.

**Comment by tinevez** [comment]
Hello @BesseLaetitia and @Raghavendrapara 

Could you please try again with the latest version of TrackMate and TrackAnalysis we just released? 
you can find them here:

https://maven.scijava.org/service/local/repositories/releases/content/sc/fiji/TrackMate_TrackAnalysis/1.0.1/TrackMate_TrackAnalysis-1.0.1.jar

https://maven.scijava.org/service/local/repositories/releases/content/sc/fiji/TrackMate_/6.0.1/TrackMate_-6.0.1.jar

Let me know if this fixes the bug for you.

**Comment by BesseLaetitia** [comment]
Hello @tinevez 

Thank you for your quick answer. I tested your last version and it works very well for us now. 

Thank you very much.

Have a nice day.

Laetitia

**Comment by tinevez** [comment]
Thanks for the feedback.
If you update Fiji now you will receive these two new versions normally, which fixes the bug.
