### ISSUE TITLE
Adding github/fiji/TrackMate to update site?

### ISSUE THREAD

**Issue by phisanti** [fiji/TrackMate#168]
Hi,

I have been looking into the code of the GitHub version of TrackMate and I can see there are some interesting functions such as `SpotFitEllipseAnalyzerFactory`. Thus, I was wondering if it would be worth it to add the https://github.com/fiji/TrackMate site directly to the ImageJ update sites list. Does that makes sense?

**Comment by tinevez** [comment]
Hello.
I got carried away and starting pushing unstable, devel code in the master. 
I am currently working on the version 7 of TrackMate that will include this AND also work.
