### ISSUE TITLE
Upload drjekyll fontchooser library.

### ISSUE THREAD

**Issue by tinevez** [fiji/TrackMate#174]
The new display settings use this library to configure the font. 
So we need to upload it or to rely on @imagejan wrapping library in SciJava (which would probably be best).

Without it, here is the error message the current version (v7.0.1) of TrackMate generates:

```java
Exception in thread "Run$_AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/drjekyll/fontchooser/FontDialog
	at fiji.plugin.trackmate.gui.displaysettings.StyleElements.lambda$linkedFontButton$13(StyleElements.java:968)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
```

**Comment by imagejan** [comment]
For completeness, here's the link to the wrapping library: https://github.com/scijava/scijava-ui-swing-fonts

**Comment by tinevez** [comment]
If it is uploaded to Fiji we could modify TrackMate to use this instead.

**Comment by imagejan** [comment]
I can cut a release and add `scijava-ui-swing-fonts` to the version management in `pom-scijava`, and as a dependency in `fiji/fiji`, if everybody is fine with that, so it gets included in future Fiji uploads.

@tinevez you mentioned issues with font styles here: https://github.com/scijava/scijava-ui-swing-fonts/commit/0d3e6182c3ad33537358917b69ab9b6bcd539be6#commitcomment-45291095, did you follow up on that? I didn't see issues in my tests.

As far as I can see from the usage here in TrackMate, you probably only care about the `fontchooser` library, and not necessarily about `scijava-ui-swing-fonts`, so it's probably fine to upload this to *Java-8* directly. If you added `fontchooser` as a proper dependency of TrackMate, it'll ultimately get there by the automated uploads anyways.

**Comment by tinevez** [comment]
1. I am still working on it. I will post my progresses here.

2. Ok so you advice sticking to the `fontchooser`upload?

**Comment by imagejan** [comment]
> so you advice sticking to the `fontchooser` upload?

Not necessarily. I just had the impression that you currently aren't using the SciJava Swing widgets for any other UI components, are you? So I don't know how much you gain from having a `@Parameter Font` when all you do is invoking the `FontDialog` from your own UI button anyways.

**Comment by tinevez** [comment]
Correct.

**Comment by tinevez** [comment]
Acknowledge https://gitlab.com/dheid/fontchooser

**Comment by tinevez** [comment]
Solved with TrackMate v7, released today.
