### ISSUE TITLE
Tracking 1 object/ making the path Bold

### ISSUE THREAD

**Issue by zkhodzhaev** [fiji/TrackMate#183]
Hello,

I tried Trackmate, and it gives all tracks at the same time. Also, the path's thickness is very thin and it's hard to use it for publications (small figures)

1. is there a way to track only one object (among many)?
2. How to make the track bold? or e.g. change the background from black to white ?

Thank you for your help.

**Comment by imagejan** [comment]
As these are _usage_ questions, I'd recommend asking them on https://forum.image.sc rather than here on GitHub.

You can filter tracks in the UI wizard, e.g. by trackID or any track feature, does that help?

**Comment by tinevez** [comment]
Solved with v7 of TrackMate.
