### ISSUE TITLE
Don't draw connections between data points in plots

### ISSUE THREAD

**Issue by haesleinhuepf** [fiji/TrackMate#186]
Hi all, hi @tinevez ,

I'm just playing with the new trackmate (7.0.5) and plotting parameters such as area over time (spots) and speed over edge time (links). In the plot, the data points are connected, and I'm not sure if they should be:
![image](https://user-images.githubusercontent.com/12660498/133906731-76234021-4fff-4a69-96d6-02625a830809.png)

Is there a way to turn the lines between the data points off? Furthermore, does it make sense to turn these lines off per default?

Thanks!

Best,
Robert

**Comment by tinevez** [comment]
Hello Robert.

The dots are connected when two of the plotted objects are linked in the model. 
For instance in the graph above, two dots are connected when the 2 links they represent share a common spot. It is super handy to follow a lineage and how numerical features change over time.
It was not working that well in version <7.

Your suggestion to not plot the connections is a good one. Especially when we will have a large of number of items to plot. I will create an issue for this suggestion.

**Comment by haesleinhuepf** [comment]
Cool! Thanks for the explanation Jean-Yves 🙂

The new plots are indeed more versatile. I like the colors also!

**Comment by haesleinhuepf** [comment]
Awesome thanks @tinevez ! 😍
