### ISSUE TITLE
TrackScheme doesn't sort tracks by their index

### ISSUE THREAD

**Issue by amitshakarchy** [fiji/TrackMate#189]
Hi all, hi @tinevez ,
I was trying to edit tracks using TrackScheme, and found it difficult working with the current way of sorting tracks.
trackIDs are sorted as you can see below, instead of in a regular order (1,2,3, etc.)
<img width="887" alt="Screenshot 2021-09-20 101243" src="https://user-images.githubusercontent.com/58327011/133967515-eabb0742-f60d-41bd-b09d-607ff0f5dcc7.png">

I tried to play with the settings and couldn't solve the problem. Am I missing something? Is there a way to re-sort the tracks?

Thanks!

Best wishes,
Amit

**Comment by tinevez** [comment]
Hello @amitshakarchy 

Normally the track should be sorted in alphanumerical order, so you should get something like Track_0, Track_1, Track_2, ..., _Track_10.
If it does no, it's a big and I will investigate.
