### ISSUE TITLE
Multi-column names when exporting spots as csv (v7.0.6)

### ISSUE THREAD

**Issue by BioinfoTongLI** [fiji/TrackMate#191]
Hi @tinevez,

Great to see the new versions of Trackmate! Can't wait to try them out!

I've noticed that the CSVs exported from `spots` button (prevously `Analysis`) have multiple column labels as below.
```
   Unnamed: 0       ID  TRACK_ID             QUALITY  ... POSITION_T  FRAME   RADIUS  VISIBILITY
0         NaN  Spot ID  Track ID             Quality  ...          T  Frame   Radius  Visibility
1         NaN  Spot ID  Track ID             Quality  ...          T  Frame        R  Visibility
2         NaN      NaN       NaN           (quality)  ...      (sec)    NaN  (pixel)         NaN
3      ID6272     6272       NaN   5.647693634033203  ...        0.0      0      2.5           1
```
Is this expected?

And also, it seems that less parameters are exported by default, e.g. Total_intensity, Estimated_diamter etc.
Is there any possibilty to get them back?

I am running v7.0.6 on Ubuntu  18.04

Best,
Tong

**Comment by tinevez** [comment]
Hello @BioinfoTongLI 

Yes this is expected. The 4 first header lines are respectively:
- the feature key
- the feature name
- the feature short name
- the feature units

Also we removed some feature analyzers in v7 as you noticed. They are detailed here:
https://github.com/fiji/TrackMate/releases/tag/TrackMate-7.0.4
