### ISSUE TITLE
Error with TrackMate 7.0.7. java.lang.NoClassDefFoundError: fiji/plugin/trackmate/gui/ConfigurationPanel

### ISSUE THREAD

**Issue by Glyphus** [fiji/TrackMate#193]
I'm having an error on multiple system with the new TrackMate release:

Some other user had a similar issue when using the GDSC plugin. However, I am not using that plugin.

I don't know much about programming as you, but tried to have a look at the source code. I found the the class "ConfigurationPanel" under "fiji/plugin/trackmate/gui/components/" and not "fiji/plugin/trackmate/gui/". Can this be the cause of the error?
How I can I solve the problem?
Thank you for your help.

> (Fiji Is Just) ImageJ 2.3.0/1.53f51; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 290MB of 12129MB (2%)
> java.lang.NoClassDefFoundError: fiji/plugin/trackmate/gui/ConfigurationPanel
>	at java.lang.Class.getDeclaredConstructors0(Native Method)
>	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
>	at java.lang.Class.getConstructor0(Class.java:3075)
>	at java.lang.Class.newInstance(Class.java:412)
>	at org.scijava.plugin.PluginInfo.createInstance(PluginInfo.java:304)
>	at fiji.plugin.trackmate.providers.AbstractProvider.registerModules(AbstractProvider.java:77)
>	at fiji.plugin.trackmate.providers.AbstractProvider.<init>(AbstractProvider.java:45)
>	at fiji.plugin.trackmate.providers.DetectorProvider.<init>(DetectorProvider.java:32)
>	at fiji.plugin.trackmate.gui.wizard.TrackMateWizardSequence.<init>(TrackMateWizardSequence.java:135)
>	at fiji.plugin.trackmate.TrackMatePlugIn.createSequence(TrackMatePlugIn.java:115)
>	at fiji.plugin.trackmate.TrackMatePlugIn.run(TrackMatePlugIn.java:96)
>	at fiji.plugin.trackmate.TrackMateRunner.run(TrackMateRunner.java:539)
>	at ij.IJ.runUserPlugIn(IJ.java:241)
>	at ij.IJ.runPlugIn(IJ.java:204)
>     at ij.Executer.runCommand(Executer.java:150)
>	at ij.Executer.run(Executer.java:68)
>	at java.lang.Thread.run(Thread.java:748)
>Caused by: java.lang.ClassNotFoundException: fiji.plugin.trackmate.gui.ConfigurationPanel
>	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
>	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
>	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>	... 17 more

**Comment by tinevez** [comment]
Hello @Glyphus 

This resembles a conflict with a remaining old version of TrackMate. Do you still have a `TrackMate_-6.x.u` in the plugins folder of Fiji?

**Comment by Glyphus** [comment]
I have no older Version of TrackMate installed. I did, however, find a solution: I have the TrackMate Batch plugin by chicoronny, which also adds the linear motion LAP tracker (https://github.com/chicoronny/RonnyTrackMate). As far as I know you also contributed to this repository. Deleting this plugin, made TrackMate work again without issue.

Is there a way to implement the linear motion LAP tracker and Batch functionality in the new TrackMate API?

Thank you for your help, though. If you had not mentioned the potential conflict with the old version, I would not have tried deleting the TrackMate Batch.

**Comment by tinevez** [comment]
Mmh I see. I had the same issue with several other projects that depend on TrackMate. The best is to contact  chicoronny and ask him for fix. Of he agrees I can help I vouched to do it for all TrackMate extensions that let me.
