### ISSUE TITLE
Features are not automatically updated when manual tracking in Trackmate v7

### ISSUE THREAD

**Issue by afellows2311** [fiji/TrackMate#194]
Hi everyone,

Since updating to the new version of Trackmate the manual tracking no longer seems to be working. It lacks track intensity measure for the spots and gives no information for tracks. This seems to occur on multiple files types. Trackmate still outputs all of these values when you use the automated tracking. 

Does anyone have an ideas why this might be occurring? I've re-downloaded Fiji a few times and am running java 8.

Best,
Alex

**Comment by tinevez** [comment]
Hello @afellows2311 and thank you for the report.
You are right! The feature values are not updated when manual tracking. They contain only the basic features:
![Screenshot 2021-10-04 at 17 36 28](https://user-images.githubusercontent.com/3583203/135880890-f0144d5f-5570-4fb1-8c5c-ecc402f5bcac.png)

I will work on a fix.

**Comment by tinevez** [comment]
While waiting on my fix you can use the action `Recompute all features` in the last panel:
![Screenshot 2021-10-04 at 17 37 45](https://user-images.githubusercontent.com/3583203/135881051-58915188-d243-48dd-8b27-fef55c98931a.png)

It will do what you need.

**Comment by afellows2311** [comment]
Thanks!
