### ISSUE TITLE
Implement an anisotropy parameter for spot fitting?

### ISSUE THREAD

**Issue by tischi** [fiji/TrackMate#201]
@tinevez I think we discussed this already some while ago, but I cannot remember the conclusion. For spots, they are often anisotropic due to the PSF. Would it be possible to accommodate this within TrackMate?

**Comment by tinevez** [comment]
Yep!
The solution would be to offer a different detector based on the LoG one, but that would alter the size of the kernel along Z. The work would be mainly about duplicating and adapting the UI and the LoG code.

Do you feel like doing it?

**Comment by tischi** [comment]
> Do you feel like doing it?

Sure 😄 

> Do I have the time?

Soooooooooon 😉

**Comment by tinevez** [comment]
Check #223 that implements just that.
