### ISSUE TITLE
ROI gets converted to overlay when swapping dimensions

### ISSUE THREAD

**Issue by lguerard** [fiji/TrackMate#203]
Hi @tinevez 

I just noticed that if I have a 3D stack with a ROI drawn on it, if I then call TrackMate and decide to swap Z and T, then the ROI is now an overlay on the image and therefore can't be modified, selected or even removed without going to Image > Overlay > Hide Overlay.

You can try this any 3D sample image in Fiji, like `confocal-series`.

Thanks !

**Comment by tinevez** [comment]
Fixed in https://github.com/fiji/TrackMate/commit/df9d401be4d0d5b3c1b243f21af0606c49d45099
