### ISSUE TITLE
Typo in TrackMate XML attribute name

### ISSUE THREAD

**Issue by quantixed** [fiji/TrackMate#208]
This is _really_ minor but there is a typo in the attribute names `feature` and `name` within `TrackFeatures` tag.

```
<Feature feature="CONFINMENT_RATIO" name="Confinment ratio" shortname="Cfn. ratio" dimension="NONE" isint="false" />
```

The same typo is therefore also in each `Track` tag.

**Comment by tinevez** [comment]
Thanks!
I will try to come up with a fix that does not break everything....
