### ISSUE TITLE
TrackMate session doesn't open .tif image sequence 

### ISSUE THREAD

**Issue by xlaub** [fiji/TrackMate#212]
Hello!

I am using TrackMate to track single particles. I use mainly the manual tracking by selecting the first particle in the first image via TrackMate Tools and let it find the next particles in the next images. 

(By the way the TrackMate Tools GUI is often not reacting. It often doesn't create a spot by pressing A and sometimes it doesn't increase the size by pressing E or Shift + E. Also when I successfully increase the size of a spot by pressing E, the spot size visually increases but there is no output, telling me what happened. Only if I increase the spot size again, the output tells me that the spot size increased, but it shows me the output of the first time I pressed E. So it lags behind one command! Similarly when I change the number of frames to be processed for finding new spots it only works if I confirm my input number by pressing “enter” twice.)

My bigger problem is another one though:
When I’m done tracking I can save the session as a .xml file on the bottom left button in the TrackMate GUI. But when I try to reopen it (Plugins -> Tracking -> Load A TrackMate File) it opens the track but on a black background. So it doesn’t open my images anymore.
I tried to save the .tif image series as a single .tif file and put the name of the file into the .xml Trackmate session file. That remedied the issue for one dataset but not for the next one I wanted to analyze. 

Any suggestions? Maybe you can tell me if I do anything wrong, or if the program is broken. 
My Fiji is up to date. Let me know if you need any more information. 
I’d appreciate it if it could be fixed soon.

Best regards
Mario

**Comment by tinevez** [comment]
Hello @xlaub 

Generally this happens when TrackMate is launched on an image **that has not yet been saved**.
If you try to save the image as ImageJ TIF before launching TrackMate, does this still happen?

**Comment by xlaub** [comment]
Hi!
So you suggest to save via File -> Save as -> Tiff, and use that file to make the tracking? 

Would you recommend to change the image properties (Ctrl+Shift+P) before saving as well? That would be swapping Z and T (which I am being asked for, when TrackMate is started) and setting the frame rate and pixel width?

Could you explain why the order would matter?

Thanks!

**Comment by tinevez** [comment]
> Hi! So you suggest to save via File -> Save as -> Tiff, and use that file to make the tracking?
> Could you explain why the order would matter?

Yes! With this TrackMate will be able to grab the link to the file it tracks, and save it along the tracks. Then, when you re-open the TrackMate file, it will open the image as well.

> Would you recommend to change the image properties (Ctrl+Shift+P) before saving as well? That would be swapping Z and T (which I am being asked for, when TrackMate is started) and setting the frame rate and pixel width?

Yes absolutely. So that you never have to it again after.

**Comment by xlaub** [comment]
Hello!

Thanks, that way it works well. Nevertheless, it is not optimal, because if you want to keep the raw data, the amount of data to be saved is doubled that way. Would be nice to be able to open the raw data directly. Maybe the issue is, that Trackmate opens the image series as a z-stack? 

Anyway, I’m grateful that it works now. :)

But I have another problem: 
I try to track multiple single particles in a huge image series. I first tried with manual annotation and track via TrackMate Tools. But it only lets me find tracks for one particle at a time. So when there are two particles close by, the tracks can jump from one particle to another. 
So I tried the algorithms, to automatically find spots, but then it finds way too many spots and tracks, and also it doesn't fill all gaps of the tracks of interest.
Since the algorithms work quite well in distinguishing particles, so that there is no mix up between neighboring particles (like in the manual annotation approach), I would like to use them, but just on a few selected spots (let’s say in the first image). Is it possible to do that? First select spots and then run the algorithm? 
Alternatively setting several ROIs in the start, would also help to confine the area where spot detection and tracking should happen. 

Many Thanks!

**Comment by tinevez** [comment]
Hello. What about having the raw data with the right metadata?

**Comment by xlaub** [comment]
Since the raw data are single .tiff images, the raw data doesn't tell what kind of stack it should be right? Isn't the session.xml responsible for opening the single tiff files as a t-stack instead of a z-stack? When the session is saved from a series of tiff files, the .xml points to filename="", which should open all files in the folder right? but that doesn't always work. If a single combined tif file is used then it is named in the filename="combined.tif"  

Any ideas for the tracking issue? :)

**Comment by tinevez** [comment]
Ok so I suggest to resave it as a ImageJ TIF file, with the dimensionality and basic metadata (pixel size) properly set (in _Image > Properties_). 
This new file could **replace** the raw data because it will match it pixel by pixel.

**Comment by xlaub** [comment]
Okay, thank you very much! I think I can live with that :)
I will open another thread for my other question.
