### ISSUE TITLE
Tracking only a selection of particles 

### ISSUE THREAD

**Issue by xlaub** [fiji/TrackMate#214]
Hello there! 

Is there a way to obtain tracks from a manually chosen selection of spots? 

I try to track multiple single particles in a huge image series. I first tried spot selection via manual annotation and tracking via TrackMate Tools. But it only lets me find tracks for one particle at a time. So when there are two particles close by, the tracks can jump from one particle to another. 
So I tried the algorithms, to automatically find spots, but then it finds way too many spots and tracks, and also it doesn't fill all gaps of the tracks of interest.
Since the algorithms work quite well in distinguishing particles, so that there is no mix up between neighboring particles (like in the manual annotation approach), I would like to use them, but just on a few selected spots (let’s say spots, that I select in the first image). Is it possible to do that? First select spots and then run the algorithm to find tracks for only these spots? 
Alternatively setting several ROIs in the start, would also help to confine the area where spot detection and tracking should happen. 

Many Thanks!

**Comment by tinevez** [comment]
Hello.

Unfortunately not right now. But Mastodon does this kind of things, and very well, in combination with a selection creator:
https://github.com/mastodon-sc/mastodon
