### ISSUE TITLE
XML files not exported properly

### ISSUE THREAD

**Issue by WilbertCYC** [fiji/TrackMate#215]
I've been running TrackMate on a Macbook for 2D cell tracking for the past month. I noticed that when I track the cells with "Manual tracking with TrackMate, the exported XML file become weird - when opened with Excel, there are more columns than a normal tracking XML file. Specifically, three columns appeared: "/particle/detection/@x/#agg", "/particle/detection/@y/#agg", and "/particle/detection/@z/#agg". In addition, there's only one X,Y position for each particle (or cell), while there should be multiple frames. This issue makes the XML file exported not recognizable by MATLAB.
Attached Zip file you will find the XML files that works (i.e., _Tracks.xml), and the one that's weird (i.e., test.xml). In the "test.xml" file, I tracked three cells manually for 48 frames. This happens to the automatic tracking as well, after I correct the tracks manually.
I've tried updating the TrackMate plug-in from 6.0.1. to 7.6.1, but it doesn't help. Thanks in advance!
<img width="414" alt="Screen Shot 2022-03-22 at 2 11 24 PM" src="https://user-images.githubusercontent.com/102165608/159549668-efa47799-1c24-4a3f-a7ae-25a5f979d51a.png">
[Archive.zip](https://github.com/fiji/TrackMate/files/8327099/Archive.zip)

**Comment by tinevez** [comment]
Hello @WilbertCYC 

This is the XML you get when you export to the simple XML file format. They just have X, Y, Z and T. 

**XML files are not meant to and cannot be opened in Excel**. 

Can you tell me what you use to import them into MATLAB? What is the command you use?

**Comment by WilbertCYC** [comment]
I imported the XML to MATLAB according to the methods described in the trackmate-manual.pdf. The commands I used was ”importTrackMateTracks”. As stated in the issue, the XML files exported from TrackMate are not consistent in format. "_Track.xml" includes all the x,y position information (256 tracks, 30 frames in maximum), whereas "test.xml", which I tracked manually with "Manual tracking with TrackMate", includes only one x,y position information for each track (3 tracks in total). Attached you will find the screenshots I took of the MATLAB codes when I read both files. I opened the files with Excel to check why one file worked but not the other, and noticed the issue I stated above. Thanks again for looking at the issue
<img width="482" alt="Screen Shot 2022-03-24 at 11 26 53 AM" src="https://user-images.githubusercontent.com/102165608/159989861-a7aa2c75-fc54-4f3f-9a85-348741218a6f.png">
<img width="501" alt="Screen Shot 2022-03-24 at 11 29 01 AM" src="https://user-images.githubusercontent.com/102165608/159989880-8716ef84-8f39-460c-adda-3aef38d7a7e0.png">
.

**Comment by tinevez** [comment]
Ok I found why the import fails:

```xml
  <particle nSpots="48">
    <detection t="23" x="1068.375" y="484.275" z="0.0" />
  </particle>
```

In the `<particle>` you have `nSpots=48` so MATLAB expects to find 48 detections. 
But there is only one so it crashes. 

The question is how what happened when we generates the faulty XML....

**Comment by WilbertCYC** [comment]
Yes. This happens most of the time for manual tracking, or when the automatically detected tracks are manually corrected. I've tried updating from v6.0.1. to 7.6.1., as well as uninstall/re-install FIJI, but the issue remains unresolved.

**Comment by christian-7** [comment]
Hello, 
I keep having the same problem. Mac or windows with the newest version of TrackMate. I used an automatic tracker with no filtering but can't import the XML into matlab. 
Any ideas of how this can be solved?
Thanks.

**Comment by tinevez** [comment]
This is being fixed:
https://github.com/fiji/TrackMate/commit/bfb7271cd7b054b1fbdbcfa90dcc81e32ad38fd7

With the next release (v7.7.x), this will be merged and the new script won't have this issue.
