### ISSUE TITLE
TrackMate Helper: Comparing two algorithms for tracking

### ISSUE THREAD

**Issue by kapoorlab** [fiji/TrackMate#221]
Hello,

Thank you for making the TrackMate CTC helper. I went through it and it seems that currently there is not an option to compare two automated algorithms versus the GT data, it only allows performing the tracking and then comparing it with GT. I however have a use case where I have tracking results exported in the CTC format as Results that I need to compare with the GT. I am currently using their linux command line code where I can get only TRA measure but I want to have other measures also like CT and BC. Is this something that you are considering to create or shall I do a PR with this feature?

**Comment by tinevez** [comment]
Hello Varun,

In this case it is best directly using the CTC Fiji plugin. You can completely bypass TrackMate.
The TM-Helper is mainly a way to optimize tracking parameters for trackers inside TrackMate.
