### ISSUE TITLE
Export label image with spot IDs

### ISSUE THREAD

**Issue by tischi** [fiji/TrackMate#225]
@tinevez 

Working on https://forum.image.sc/t/trackmate-dealing-with-masks/68004

I guess this needs updating?

```
/**
	 * Creates a new label {@link Img} of {@link UnsignedShortType} where the
	 * spots of the specified model are painted as ellipsoids taken from their
	 * shape, with their track ID as pixel value.
	 * 
```

Because in the case of masks they are not painted as ellipsoids but as the actual masks?

**Comment by tischi** [comment]
Second question: In your repo is that some "run" method that launches ImageJ such that I could test what I am developing? Even better would be some script that already does some tracking such that I immediately end up at the export UI. Or how would you do this (i.e. develop such a new feature)?

**Comment by tischi** [comment]
Third question: Should I develop against `master` or some other branch?

**Comment by tischi** [comment]
Fourth question:

<img width="442" alt="image" src="https://user-images.githubusercontent.com/2157566/172616470-326c342a-97c9-42e5-9a4b-eb676878ff42.png">

Should we add a checkbox here:

`[ ] Use spot IDs as labels`

**Comment by tinevez** [comment]
Fixed with https://github.com/fiji/TrackMate/commit/e13e6198437f3aec3d70270485a0c27e6b4b12f2
