### ISSUE TITLE
How to Identify subtracks in tracking CSV 

### ISSUE THREAD

**Issue by emmanuel-contreras** [fiji/TrackMate#231]
First of all thank you for the fantastic software! We are working on time lapse images of HeLa/143B cells to quantify their metabolism in mitosis. I have been trying out trackmate and it has worked well so far but I've run into a issue you may have some insight into.

The issue I am running into is during a splitting event, I'm having trouble figuring out how to match the spot on the subtracks given that the whole track (parent + children) is labeled as 0 on the CSV file. I can see that there are two spots from the same track on frames where the parent has split but can't figure out which spot belongs to what spot on the subsequent frames. Maybe there is a variable on the csv that can help with this? something like track "0" for parent and "0-1" and "0-2" would be useful to see what track spots belong to after they split. 

Thank you!

![image](https://user-images.githubusercontent.com/14666496/188191321-e6b89639-63c7-44be-9648-8598366e613f.png)

**Comment by tinevez** [comment]
Thanks for the kind words!
I am not sure of a way yet, but what about discussing this on the https://forum.image.sc ?
The discussion could be beneficial to others.
