### ISSUE TITLE
On windows, the TrackScheme toolbar does not look so good.

### ISSUE THREAD

**Issue by tinevez** [fiji/TrackMate#50]
![screenshot](https://cloud.githubusercontent.com/assets/3583203/4098422/42527102-301e-11e4-961c-cc11319adba8.png)

**Comment by royfrancis** [comment]
Using Win 7. The TrackScheme bar rarely works or loads properly. Even if it does, it shows the points connected by lines but I have never seen the snapshot from images showing up.

**Comment by tinevez** [comment]
@royfrancis it seems to be an unrelated issue.
Could you elaborate using another issue? I will need a screenshot and example files.
best
jy

**Comment by royfrancis** [comment]
![screenshot 2015-06-13 16 51 01](https://cloud.githubusercontent.com/assets/5083500/8144765/433d82e4-11ed-11e5-99d3-e0ea3416ab71.png)

After I click on 1, the progress bar at 2 shows collecting thumbnails, but at the end of the progress, nothing happens.
My file is at this location (temporary link):
https://dl.dropboxusercontent.com/u/78814791/sites/trackmatecheck/1-Converted.tif
Default calibration. I used Dog Detector with diameter 7px and threshold 8. Everything else was default. No filtering.

**Comment by royfrancis** [comment]
New issue opened.

**Comment by tinevez** [comment]
I need the xml file as well. 

<div>-------- Original message --------</div><div>From: Roy Francis <notifications@github.com> </div><div>Date:13/06/2015  17:04  (GMT+01:00) </div><div>To: fiji/TrackMate <TrackMate@noreply.github.com> </div><div>Cc: Jean-Yves Tinevez <jeanyves.tinevez@gmail.com> </div><div>Subject: Re: [TrackMate] On windows, the TrackScheme toolbar does not look so
  good. (#50) </div><div>
</div>
After I click on 1, the progress bar at 2 shows collecting thumbnails, but at the end of the progress, nothing happens.
My file is at this location (temporary link):
https://dl.dropboxusercontent.com/u/78814791/sites/trackmatecheck/1-Converted.tif
Default calibration. I used Dog Detector with diameter 7px and threshold 8. Everything else was default. No filtering.
