### ISSUE TITLE
No thumbnails in TrackScheme view

### ISSUE THREAD

**Issue by royfrancis** [fiji/TrackMate#60]
![screenshot 2015-06-13 16 51 01](https://cloud.githubusercontent.com/assets/5083500/8144765/433d82e4-11ed-11e5-99d3-e0ea3416ab71.png)

After I click on 1, the progress bar at 2 shows collecting thumbnails, but at the end of the progress, nothing happens.
My file is at this location (temporary link):
https://dl.dropboxusercontent.com/u/78814791/sites/trackmatecheck/1-Converted.tif
XML link:
https://dl.dropboxusercontent.com/u/78814791/sites/trackmatecheck/1-Converted.xml
Default calibration. I used Dog Detector with diameter 7px and threshold 8. Everything else was default. No filtering.

**Comment by tinevez** [comment]
Hi @royfrancis 
The tiff file has incorrect dimensionality: it states that it has 50 z-slices. If you now set to have 50 frames and 1 z-slices, the thumbnails are found correctly.
