### ISSUE TITLE
Consider expanding MATLAB integration

### ISSUE THREAD

**Issue by hinerm** [fiji/TrackMate#63]
@etarena pointed out that there may be opportunity for enhanced integration as a result of recent [ImageJ-MATLAB](https://github.com/imagej/imagej-matlab) work.

Some potential ideas:
- Script templates that would take track results in Fiji, import them to MATLAB and perhaps also run some analysis. This would be a cool and clear way to demonstrate the usefulness of the framework, and also would require '@Parameter'ization of TrackMate output - which could be used in other contexts!
- A [MATLABCommand](https://github.com/imagej/imagej-matlab/blob/imagej-matlab-0.4.1/src/main/java/net/imagej/matlab/ImageJMATLABCommands.java) plugin with TrackMate utility methods (i.e. [importTrackMateTracks](https://github.com/fiji/TrackMate/blob/master/scripts/importTrackMateTracks.m)). This is a little safer than distributing separate '.m' functions, since it would be part of the versioned TrackMate artifact.

**Comment by hinerm** [comment]
@tinevez - look at the fun stuff we could work on if you were at the hackathon! :octopus:

**Comment by tinevez** [comment]
@hinerm you're killing me! :)
10 people out 11 told me I am stupid not to go already

**Comment by tinevez** [comment]
Hi @hinerm 
On this subject I have made some progresses, though they do not follow your recommendations. 
I made plain MATLAB functions that can import a TrackMate file as a MATLAB directed graph, much like what we have inside TrackMate. 

Any advice of how I should go on with this? Just release them in the `script` folder? Something else?

**Comment by hinerm** [comment]
> Any advice of how I should go on with this? Just release them in the script folder?

I think this sounds reasonable!

**Comment by tinevez** [comment]
Done along with the TrackMate publication in 2017. 
Documented in the manual.
