### ISSUE TITLE
CSV export

### ISSUE THREAD

**Issue by cmci** [fiji/TrackMate#64]
Hi @tinevez, 

Great tool! and I have a question, It could be a solved / answered issue: could the resulted tracks be exported as a csv file (time point, coordinates, intensity...)?

thanks,
Kota

**Comment by tinevez** [comment]
Hi @cmci 
So what you can if you want something simple is use the 'Analysis' button on the 'Configure view' panel (the 2nd to last, which allows configuring the display). It will pop up 3 ImageJ tables, one of them containing spots sorted by track, and time. You can save it as CSV. 
Please tell me if this is what you are looking for.
best

**Comment by cmci** [comment]
Thanks a lot!
