### ISSUE TITLE
Threshold value is not strictly used while tracking particles

### ISSUE THREAD

**Issue by ctrueden** [fiji/TrackMate#69]
Migrated from [Fiji BugZilla issue #1160](http://fiji.sc/bugzilla/show_bug.cgi?id=1160):
> Threshold value in Trackmate is not stricktly used while tracking particles. most of the time particles considered in tracking analysis have intensity values much lower than the threshold value set before starting the analysis.
>
> Threshold value is not used stricktly during the tracking of particles. 
> Problematic when user requires specific particles to track.

**Comment by tinevez** [comment]
I do not confirm this bug at all. 
Could you send me a use case that would make a bug clear?

**Comment by tinevez** [comment]
No feedback from reporter.
