### ISSUE TITLE
Toggle display of spots that are not in currently selected plane

### ISSUE THREAD

**Issue by tischi** [fiji/TrackMate#71]
Hello!

When using TrackMate on big 3D data sets display of spots that are not in the currently selected plane can obstruct the view on the data and makes it (in my case) impossible to set sensible Threshold parameters for the spot detection.

This applies to the following panels:

- Settings for detector
- Set filters on Spots

I think a checkbox "Show out-of-plane spots" would be an essential feature for me.

Best, Christian

**Comment by tinevez** [comment]
Hi @tischi 
This settings already exists. You can limit the display depth in the panel where views are configured. By setting it to a small value, you can get what you want.

**Comment by tischi** [comment]
Hi Jy,

That's great! 

However the only thing I could find was in "Display Options" the feature "Limit drawing depth".
But to get there I have to go once through the whole workflow and then back again to to beginning, which takes very long if you have >800000 spots. 
I tried setting this on a dummy data set and then reopen trackmate on a real data set, but it did not keep my setting of Drawing depth = 3pixels
Surely I am missing something!

**Comment by tinevez** [comment]
No you are not. I see what you mean.
What should have been done is to separate display options from the GUI wizard process. Indeed it makes no sense to change display settings only at the last part of the process.
Unfortunately, this poor design is not easily changed, and I fear you will have to live with it...

**Comment by imagejan** [comment]
Wouldn't it be possible to somehow get the current `HyperStackDisplayer` and call `HyperStackDisplayer#setDisplaySettings(TrackMateModelView.KEY_DRAWING_DEPTH, value)`? I guess the difficulty is to get the current instance of `HyperStackDisplayer` just after it was instantiated, right?

**Comment by tinevez** [comment]
@imagejan  That would work. Now we have to think about how to get the right instance. 
Something like IJ WindowManager I guess.

**Comment by tischi** [comment]
I found a workaround, which is to 

i) set the crop in the first window to a small region
ii) go through the whole workflow using NN linking to be fast
iii) change display settings
iv) go all the way back and reset the crop
v) start the actual workflow

not beautiful, but works.

**Comment by tinevez** [comment]
I thought about this and I think a proper way would be to have a display settings window that can be accessed at any time. I will create an issue about this, but don't expect to get it this year...
