### ISSUE TITLE
Add new trajectory visualization

### ISSUE THREAD

**Issue by thorstenwagner** [fiji/TrackMate#73]
Dear Jean-Yves,

it would be nice if you could add a trajectory visualization which only shows the trajectory when it is active. I recently need that and implemented it in an extra imagej plugin:
https://github.com/thorstenwagner/ij-trackmate-viewer

Cheers,
Thorsten

**Comment by tinevez** [comment]
Hi Thorsten. 
Good idea, severalpeople asked for it. 
I have to integrate this on the GUI and find the time.

**Comment by thorstenwagner** [comment]
Nice :-)

**Comment by tinevez** [comment]
Well, we'll see when it's done :/
