### ISSUE TITLE
Add FeatureFilter for spots contained in the current ROI

### ISSUE THREAD

**Issue by imagejan** [fiji/TrackMate#74]
It would be useful to restrict the detected spots to a given (freehand or composite) ROI by simply filtering on the value of `imp.getRoi().contains(int x, int y)` by creating a `FeatureFilter` for that.

I couldn't find that functionality, so far ROIs are only respected during spot detection preview.

**Comment by tinevez** [comment]
Hi @imagejan 
This is tricky, as FeatureFilter only take scalar input. The closest I have is the use of Spot.X, Y as filters. Could you develop a bit? Just for your slow friend?

**Comment by imagejan** [comment]
Hi @tinevez 
the actual use case is when you want to track spots in the cytoplasm of a cell but not in the nucleus, and not in potential neighboring cells. You draw a freehand ROI, detect the spot and it would be great to be able to simple filter the spots according to if they are in ROI. Of course this can also be done by masking before starting TrackMate, but filtering by ROI would make it much more user friendly :)

**Comment by tinevez** [comment]
I am hesitating on this one because I cannot add it on the wizard without disrupting how it flows currently. 
Best thing I can think of is to make it an Action, callable from the last panel. Do you want to have a go for it? 
http://fiji.sc/How_to_write_custom_actions_for_TrackMate

**Comment by tinevez** [comment]
Current version takes into account a ROI, even freehand, for detection.
