### ISSUE TITLE
Trackmate Scripting Output to CSV?

### ISSUE THREAD

**Issue by Christopher-Ng** [fiji/TrackMate#82]
I am currently writing a few Trackmate scripts to automate my image processing that I had using the GUI for initially. 
It has dramatically speeded up my work but I love the "Track Statistics" CSV that I was able to save from the Analysis button, as it was easily importable into excel etc. Is there a way to create a table from the feature model similar to the "Track Statistics" table?

Thanks!

**Comment by tinevez** [comment]
I don't think you can do it in IJ1 macro, as there is no command.
In python you can take inspiration from this script
http://imagej.net/Scripting_TrackMate#Export_spot.2C_edge_and_track_numerical_features_after_tracking
and add commands to save the IJ1 table as CVS.

**Comment by ctrueden** [comment]
> I don't think you can do it in IJ1 macro, as there is no command.

Well, there is [eval](http://imagej.net/developer/macro/functions.html#eval). But it's still not object-oriented.

**Comment by chillywings** [comment]
Sorry to revive an old thread, but has anyone figured this out? 

I've managed to be able to export the data to an xml file using `ExportTracksToXML.export( model, settings, File)`, however I find that data difficult to work with (and attempting to load this data into a trackmate instance via the GUI or a script produces errors). 

`ExportStatsToIJAction.execute( trackmate )` produces the tables that I want, however I would like to be able to export them to a csv/xlsx rather than imageJ tables. Even better would be if I could export to a sheet within a csv/xlsx file.

If anyone knows any solutions I would greatly appreciate it.

**Comment by Christopher-Ng** [comment]
Hi @chillywings I never came up with a good solution, but what do the ImageJ tables look like? Do they look like the results tables from other analyses? Those can be saved to a csv (or txt file) just by Saving. I do something like that for other macros that I have.

**Comment by tinevez** [comment]
Hi @chillywings 
@Christopher-Ng  is right, you should be able to save the IJ tables as CSV. I do this all the time to send stuff to Excel.

**Comment by chillywings** [comment]
Hey guys,

The tables put out from `ExportStatsToIJAction.execute( trackmate )` are identical to the ones put out by the GUI. My initial idea was of course to save the tables, however for some reason the tables are inaccessible to the IJ window manager so the saveAs() command can't be used. See the following:
https://forum.image.sc/t/trackmate-scripting-automatically-exporting-spots-in-tracks-links-in-tracks-tracks-statistics-and-branching-analysis-to-csv/6256/5

@tinevez you suggested reading the features directly from the model, however I'm not sure how to save those to a csv.

**Comment by tinevez** [comment]
Rmlml. The solution would be to have a way for the `ExportStatsToIJAction` to return the tables it created. But it would add fields in to the class that could be null before you call `execute` and methods. This is a bit ugly. Any other idea people?

**Comment by tinevez** [comment]
Somehow did you try to save to CSV in python? Like with this?
https://docs.python.org/2/library/csv.html

**Comment by chillywings** [comment]
Hey tinevez,

No, but I'll give it a shot down the road. For now I've just resorted to dealing with xml files and that's working for me. I may still need excel data at some point, so if I figure it out I'll post an update. 

Thanks,
Marcus

**Comment by yifnzhao** [comment]
Hi folks, not sure if this has been solved but for my analysis I have written a python script to get the tracks and links statistics from TrackMate xml files, in addition to the spots which can be extracted by [pytrackmate](https://github.com/hadim/pytrackmate) repo. Please feel free to fork and make use of [it](https://github.com/yifnzhao/TrackMate_XML_to_CSV).

**Comment by matthiasLEBEC** [comment]
Hey I had this exact problem:
I want to export the output table of the spotdetection "ExportAllSpotsStatsAction().execute(trackmate)"
This table is open in a ImageJ table that at first I had trouble to save using a command.

Finally I did this and it seems to work just fine:
`from ij import IJ, ImagePlus, ImageStack
dir = "D:/Matthias_LE_BEC/ImageAnalysis/ImageJ_CustomMacro/"
IJ.saveAs("text",  dir + "thisIsTheFileName" + ".csv")`

The "text" is the important part, see also: [https://imagej.nih.gov/ij/developer/macro/functions.html#save](url)

Cheers, 
Matthias

**Comment by imagejan** [comment]
For what it's worth, with https://github.com/trackmate-sc/TrackMate/commit/3867904ad85d30c062a7fdcd71d6befee99e4b84, exporting to csv (both from the Tracks Table and the All Spots Table) is now possible directly from scripts:

```python
#@ TrackMate tm
#@ File (style="save") csvFileSpots
#@ File (style="save") csvFileTracks
#@ File (style="save") csvFileAllSpots

from fiji.plugin.trackmate.visualization.table import TrackTableView
from fiji.plugin.trackmate.visualization.table import AllSpotsTableView
from fiji.plugin.trackmate import SelectionModel
from fiji.plugin.trackmate.gui.displaysettings import DisplaySettings

# Create default SelectionModel and DisplaySettings
sm = SelectionModel(tm.getModel())
ds = DisplaySettings()

# Save spot and track statistics
trackTableView = TrackTableView(tm.getModel(), sm, ds)
trackTableView.getSpotTable().exportToCsv(csvFileSpots)
trackTableView.getTrackTable().exportToCsv(csvFileTracks)

# Save all spots table
spotsTableView = AllSpotsTableView(tm.getModel(), sm, ds)
spotsTableView.exportToCsv(csvFileAllSpots.getAbsolutePath())
```
