### ISSUE TITLE
Linear LAP Tracker fails when no spots is present in the first frame

### ISSUE THREAD

**Issue by hadim** [fiji/TrackMate#86]
I have the following error : 

```
Exception in thread "TrackMate tracking thread" java.lang.IllegalArgumentException: loops not allowed
    at org.jgrapht.graph.AbstractBaseGraph.addEdge(Unknown Source)
    at fiji.plugin.trackmate.tracking.kalman.KalmanTracker.process(KalmanTracker.java:284)
    at fiji.plugin.trackmate.TrackMate.execTracking(TrackMate.java:254)
    at fiji.plugin.trackmate.gui.descriptors.TrackingDescriptor$1.run(TrackingDescriptor.java:55)
```

Using last Fiji 3.3.0 version.

**Comment by hadim** [comment]
It's weird cuz it's working "sometime" with different images on my dataset... I'll let you know as soon as I can find the common parameters that arise when it's not working,

**Comment by tinevez** [comment]
Apparently it's trying to link a spot with itself, which is forbidden. 
I suspect either
- a problem with multihtreading.
- a problem with spot equality.

Any chance you would update the title of the issue to something more specific?

**Comment by hadim** [comment]
If you have idea for more tests I could do, tell me because I can't find a strict way to reproduce the error.

**Comment by tinevez** [comment]
To be honest I cannot reproduce the problem. But it does not mean it is not real.

What would help as always is an image with parameters to reproduce the problem here.

For the multithreading problem, try to see if setting the number of threads available to the tracker to exactly 1 solves it or not.

**Comment by hadim** [comment]
I got it. This is because the first frame is just a black image that contain no spots. If I remove the first image, I don't have the bug anymore.

(I have a first only black image because I do a subtraction in time of stack)

**Comment by tinevez** [comment]
So thisis a bug. TrackMate should not fail there.
Congratulations! Can you change the name of the issue again?
