### ISSUE TITLE
Choosing output data for Trackmate 

### ISSUE THREAD

**Issue by Cotton-eye-Joe** [fiji/TrackMate#88]
Hello everybody,
As the title says, I was wondering if it would be possible to show only some results when i click TrackMate's 'Analysis' tab. Right now the table shows TrackID,speeds, location, etc.. I would like it to just show the TrackID and mean velocities. Is this possible?
I have already made another post on the ImageJ forum about this  - http://forum.imagej.net/t/choosing-output-data-for-trackmate/2466

Thanks,
-Praveen

**Comment by tinevez** [comment]
Hi Praveen.
This is not possible at the moment.
The shortest route is to create your own Action module that does that.
A longer route would be to re-engineer the analysis module handling in TrackMate, and build a GUI that lets the user choose what analysers are activated in a TrackMate session. 
I keep track of this as a feature enhancement request.

**Comment by hadim** [comment]
@tinevez is that possible to run the GUI, do the detection and tracking and get the TrackMate object in the Python script GUI of Fiji ?

This way it's easy to extract the informations you want but I am not sure it's possible...

**Comment by tinevez** [comment]
@hadim At the moment if you want to catch the Model in a script from the GUI, you have to save it to a file, then reload it from the script. 
There are not static accessors for TrackMate instances. So you cannot get the Model instance you modify in a GUI, lest you launched the GUI from a script.
But this is a different issue.

**Comment by hadim** [comment]
Yes sure I was just wondering :-)
