### ISSUE TITLE
Export track Stack - user specified parameters 

### ISSUE THREAD

**Issue by Rjankele** [fiji/TrackMate#93]
Hi, thanks for developing TrackMate.

Would it be possible to specify the area around the spot when exporting track stack? 
It would be also extremely useful to export whole 4D hyperstack not only the mid-plane (we have data in 3D + time in 2 channels and the features we are interested in are in the other channel outside of the tracked blob...) 

Thanks
Radek

**Comment by tinevez** [comment]
Hi Radek,

This is possible: use the _Spot display radius ratio_ setting in the _Display options_ panel, then rerun the action. It will use the ratio you set to determine the size of the window.

**Comment by Rjankele** [comment]
Hi,
thanks I haven't realised this . How about that z-slices?
We noticed that when using export track stack with manually tracked track, it exports only single black/empty image 48x48px. Is that a known bug?

**Comment by tinevez** [comment]
I cannot reproduce the issue. Can you post the steps to reproduce it?

**Comment by Rjankele** [comment]
with track ID 0 and 6 in following xml file I get only one a single time-point snapshot (it is not black now, problem was settings of contrast...), but for track ID 2 I get a track stack. I don't see why.

[W14.tif-poorman3D-rigidbody-maxintensity.xml-oocyte-7-8-9tracks.xml.zip](https://github.com/fiji/TrackMate/files/799558/W14.tif-poorman3D-rigidbody-maxintensity.xml-oocyte-7-8-9tracks.xml.zip)

But this still doesn't answers my previous question whether I could get all slices from a given frame in which the spot is located...

**Comment by tinevez** [comment]
Hey @Rjankele 
I do not have the image attached so I cannot investigate. 

As for your question, yes you are right actually!
The 3D version of the stack is only present in MaMuT, not in TrackMate. I will make an issue to put it there for next version.

**Comment by Rjankele** [comment]
That would be great.
The Image is gigantic, so I am now producing cropped image to replicate the problem to be able to upload it.
