### ISSUE TITLE
MultiChannel SpotSegmentation via API

### ISSUE THREAD

**Issue by tischi** [fiji/TrackMate#99]
I am trying to use the TrackMate API for multi-channel spot detection. As I did not find a "per-channel" logic within the current API, I am instantiating a new trackmate.model for each channel and store all the models in a array:

        segmentationResults.models = new Model[channels.length];
        segmentationResults.channels = channels;

        for( int channel : channels) {

            Model model = new Model();
            segmentationResults.models[channel] = model;
            
            Settings settings = new Settings();
            settings.detectorFactory = new DogDetectorFactory<>();
            }

            Roi roi = imp.getRoi();
            if (roi != null && roi.isArea()) {
                Point3D regionOffset = new Point3D(roi.getBounds().getX(), roi.getBounds().getY(), 0);
                Point3D regionSize = new Point3D(roi.getBounds().getWidth(), roi.getBounds().getHeight(), imp.getNSlices());
                settings.xstart = (int) regionOffset.getX();
                settings.xend = settings.xstart + (int) regionSize.getX() - 1;
                settings.ystart = (int) regionOffset.getX();
                settings.yend = settings.ystart + (int) regionSize.getY() - 1;
                settings.zstart = (int) regionOffset.getX();
                settings.zend = settings.zstart + (int) regionSize.getZ() - 1;
            } else {
                Point3D regionOffset = null;
                Point3D regionSize = null;
            }

            settings.setFrom(imp);
            settings.detectorSettings = settings.detectorFactory.getDefaultSettings();
            settings.detectorSettings.put(DetectorKeys.KEY_TARGET_CHANNEL, channel);
            settings.detectorSettings.put(DetectorKeys.KEY_DO_SUBPIXEL_LOCALIZATION, true);
            settings.detectorSettings.put(DetectorKeys.KEY_RADIUS, segmentationSettings.trackMateSpotSize);
            settings.detectorSettings.put(DetectorKeys.KEY_THRESHOLD, segmentationSettings.trackMateSpotThreshold);

            // TODO: can one not use the tracker if one only wants to find spots?
            settings.trackerFactory = new SparseLAPTrackerFactory();
            settings.trackerSettings = LAPUtils.getDefaultLAPSettingsMap();
            settings.trackerSettings.put(TrackerKeys.KEY_LINKING_MAX_DISTANCE, TrackerKeys.DEFAULT_LINKING_MAX_DISTANCE);
            settings.trackerSettings.put(TrackerKeys.KEY_GAP_CLOSING_MAX_DISTANCE, TrackerKeys.DEFAULT_GAP_CLOSING_MAX_DISTANCE);
            settings.trackerSettings.put(TrackerKeys.KEY_GAP_CLOSING_MAX_FRAME_GAP, TrackerKeys.DEFAULT_GAP_CLOSING_MAX_FRAME_GAP);

            // settings.detectorFactory.

            TrackMate trackmate = new TrackMate(model, settings);

            // Process (spot detection and tracking)
            if (!trackmate.checkInput()) {
                log("Configuration error: " + trackmate.getErrorMessage());
                //return segmentationResults;
            }
            // TODO: below code works for only segmenting the spots, but I could not see them in the HyperStackDisplayer
            //if (!trackmate.execDetection()) {
            //    log("Detection error: " + trackmate.getErrorMessage());
            //    //return segmentationResults;
            //}
            if (!trackmate.process()) {
                log("Processing error: " + trackmate.getErrorMessage());
                //return segmentationResults;
            }
            //
            // Store results in segmentationResults
            //
            log("Number of spots: " + model.getSpots().getNSpots(false));

        }

        return segmentationResults;

Is that a good idea? In fact, for me, it works, and I am really very happy with the TrackMate API! :-)

The issue for me comes when I am trying to display the spot detection results for the different channels together, each channel with a different color. I was playing around quite a bit also trying to directly use the SpotOverlay class, but I could not get it to work. I thought about having something like this:

        HyperStackDisplayer[] hyperStackDisplayers = new HyperStackDisplayer[models.length];
        
        for ( int i=0; i<hyperStackDisplayers.length; i++ ) 
        {
            
            SelectionModel selectionModel = new SelectionModel(models[i]);
            hyperStackDisplayers[i] = new HyperStackDisplayer(models[i], selectionModel, imp);
            hyperStackDisplayers[i].setDisplaySettings("Color", SOMEHOW_CHOOSE_A_COLOR_FOR_EACH_CHANNEL);
            hyperStackDisplayers[i].render();
        }
        

However, for me, the respective next HyperStackDisplayers clears the overlay generated by the previous one (the SpotOverlay had the same issue for me) and thus I cannot see all spots together. 

Am I doing something work, or you have other suggestions?

**Comment by tischi** [comment]
I found a solution (code below), putting all spots into one model and then assigning a color feature.
Do you think that is a good solution?

    public void showOverlayUsingTrackMateHyperStackDisplayer()
    {
        // get the multi-channel TrackMate results
        Model[] models = segmentationResults.models;

        Model modelOverlay = new Model();
        modelOverlay.setLogger(Logger.IJ_LOGGER);
        Settings settings = new Settings();
        settings.addTrackAnalyzer(new TrackIndexAnalyzer());
        ModelFeatureUpdater modelFeatureUpdater = new ModelFeatureUpdater( modelOverlay, settings );

        int frame = 0; // zero-based !!

        modelOverlay.beginUpdate();
        for ( int iChannel = 0; iChannel < segmentationResults.channels.length; iChannel++)
        {
            Model model = models[iChannel];
            SpotCollection spotCollection = model.getSpots();
            log("Channel: "+segmentationResults.channels[iChannel]+"; Number of spots: "+spotCollection.getNSpots(false));
            for ( Spot spot : spotCollection.iterable(false) )
            {

                spot.putFeature("COLOR", (double) iChannel + 1);
                modelOverlay.addSpotTo(spot, frame);

            }
        }
        modelOverlay.endUpdate();

        SpotCollection spotCollection = modelOverlay.getSpots();
        log("Total number of spots: " + spotCollection.getNSpots(false));

        SpotColorGenerator spotColorGenerator = new SpotColorGenerator(modelOverlay);
        spotColorGenerator.setFeature("COLOR");
        spotColorGenerator.setMinMax(1.0,3.0);
        //spotColorGenerator.autoMinMax();
        spotColorGenerator.activate();

        InterpolatePaintScale interpolatePaintScale = new InterpolatePaintScale(1.0, (double)segmentationResults.channels.length);
        interpolatePaintScale.add(1.0, Color.red);
        interpolatePaintScale.add(2.0, Color.green);
        interpolatePaintScale.add(3.0, Color.white);

        SelectionModel selectionModel = new SelectionModel(modelOverlay);
        //selectionModel.addSpotToSelection(spotCollection);
        HyperStackDisplayer hyperStackDisplayer = new HyperStackDisplayer(modelOverlay, selectionModel, imp);

        hyperStackDisplayer.setDisplaySettings(hyperStackDisplayer.KEY_COLORMAP, interpolatePaintScale);
        hyperStackDisplayer.setDisplaySettings(hyperStackDisplayer.KEY_SPOT_COLORING, spotColorGenerator);
        hyperStackDisplayer.setDisplaySettings(hyperStackDisplayer.KEY_TRACKS_VISIBLE, false);
        hyperStackDisplayer.setDisplaySettings(hyperStackDisplayer.KEY_SPOTS_VISIBLE, true);
        hyperStackDisplayer.setDisplaySettings(hyperStackDisplayer.KEY_SPOT_RADIUS_RATIO, 1.0);

        hyperStackDisplayer.render();
        hyperStackDisplayer.refresh();

    }

**Comment by imagejan** [comment]
That looks like a very nice solution to me 😄 

The only thing that confuses me is the name of the variable `segmentationResults`: because there's no [segmentation](http://imagej.net/Segmentation) performed anywhere, the spots are merely a collection of coordinates and do not segment your image into foreground and background regions...

**Comment by tischi** [comment]
The reason for the name is that I want to write my code generic enough to also hold other segmentation results such as provided by the 3DImageSuite. Basically, the class segmentationResults is just a container that has member variables such as TrackMate models, but could be also anything else. The idea is that TrackMate DoG is just one option for SpotDetection, but the user could also select other ones:

https://github.com/tischi/imagej-open-stacks-as-virtualstack/blob/master/open_stacks_as_virtual_stack_maven/src/main/java/bigDataTools/AnalyzeFishSpotsGUI.java#L52

I have all the code here:
https://github.com/tischi/imagej-open-stacks-as-virtualstack/tree/master/open_stacks_as_virtual_stack_maven/src/main/java/bigDataTools
It is still messed up with other code, but if you are interested you could only look at the java files
Analyze*.java
Segment*.java

**Comment by tischi** [comment]
Hi again,

I just realized that my code is in fact not working, as it still always uses the default **_Jet_** InterpolatePaintScale for painting the spot. I found this line of code and it seems to be hard-coded:

https://github.com/fiji/TrackMate/blob/master/src/main/java/fiji/plugin/trackmate/visualization/SpotColorGenerator.java#L26

In below code:

        HyperStackDisplayer hyperStackDisplayer = new HyperStackDisplayer(modelOverlay, selectionModel, imp);
        hyperStackDisplayer.setDisplaySettings(hyperStackDisplayer.KEY_COLORMAP, WHATEVER);
        hyperStackDisplayer.setDisplaySettings(hyperStackDisplayer.KEY_SPOT_COLORING, spotColorGenerator);
        hyperStackDisplayer.setDisplaySettings(hyperStackDisplayer.KEY_TRACKS_VISIBLE, false);
        hyperStackDisplayer.setDisplaySettings(hyperStackDisplayer.KEY_SPOTS_VISIBLE, true);
        hyperStackDisplayer.setDisplaySettings(hyperStackDisplayer.KEY_DISPLAY_SPOT_NAMES, true);
        hyperStackDisplayer.setDisplaySettings(hyperStackDisplayer.KEY_SPOT_RADIUS_RATIO, 1.0);
        hyperStackDisplayer.render();
        hyperStackDisplayer.refresh();

the **hyperStackDisplayer.KEY_COLORMAP, WHATEVER** seems to be ignored for the spot coloring. Is that really the case or am I doing something wrong? Is there any way how I could control the colormap for the spot-coloring?

**Comment by imagejan** [comment]
I submitted this pull request https://github.com/fiji/TrackMate/pull/90 a while ago to change the standard color map to Viridis (because it is perceptually uniform and in general far better than the ugly Jet, IMHO). As you see there, the color map is currently hard-coded. If you find time to investigate how to make it configurable from the UI, that would be great.

**Comment by tischi** [comment]
Thank you for the fast answer! Getting into the TrackMate code deep enough to create a pull request for a real solution is not realistic for me in the short term, but I will keep it in mind and hopefully find some time in the future! Looks like for now I have to live with the Jet.
